### ISSUE TITLE
Merge frontend

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#29]
Merge the [frontend code](https://github.com/opencalifornia/disclosure-frontend-alpha) into the disclosure-backend repo.

**Comment by adborden** [comment]
#34 roughly shows how this would be done. If you have any comments, please add them to the PR. Right now, the approach seems clean enough that we can build on, there are just a handful of pending issues.
- [x] Rename folder js -> frontend.
- [x] Remove bower.
- [ ] Integrate a better dev cycle.

**Comment by adborden** [comment]
#37 takes care of the first two.

**Comment by adborden** [comment]
To see this ongoing work, you can checkout branch [frontend-merge](/caciviclab/disclosure-backend/tree/frontend-merge). I've prefixed "in development" branches with `frontend-m/`

**Comment by adborden** [comment]
This is on hold. I have a branch frontend-m/browserify-pipeline with the latest. The biggest issue is that the way django-pipeline works is it copies everything to the static root, and then builds things there. That doesn't work well for us, because node_modules get's copied, with a lot of dev dependencies.

You can kind of mangle the paths to trick it into working, but it's not ideal--certainly confusing when your require paths don't always match up with the directory structure. Anyway, without any feedback from some of the frontend folks, I'm shelving this work.

The current plan is to host the frontend app at disclosure.caciviclab.org which can talk to the django api on another domain.

**Comment by bcipolli** [comment]
It's unclear to me why this would be desirable. In my eyes, the back-end app is an independent API for any front-end. The front-end app is simply one (of potentially many) apps to process and display those data.

For me, the current architecture (separate repos) is the right one.

**Comment by tdooner** [comment]
Yeah, we kind of stopped doing this.

The original intention was to simplify the development process and allow us to make cross-cutting changes without separate deploy processes and communication overhead. And it eases the set-up burden because we would only have one set of instructions to follow (and maintain!) instead of two.

But yeah, the structure of the frontend repo is pretty opinionated, and so too is the structure of django, so it's probably easiest to just let both projects live how they want to live... in separate repos.

I'm going to close this issue for now so it doesn't distract us. If we really _really_ want to do this for some reason we can revisit later.
