### ISSUE TITLE
Add documentation of how to create settings_local.py for development credentials

### ISSUE THREAD

**Issue by rkiddy** [caciviclab/disclosure-backend#38]
Rather than have everyone put their database username and password inside of the settings.py file, one can use one's my.cnf file. There is then no chance someone will accidentally check their username and password information into the repository.

It would be better to put this into the settings.py file, rather than put in something like "username=root", which I hope people do not use by default.

The settings.py file can contain:

```
 DATABASES = {
      'OPTIONS': {
          'read_default_file': '/path/to/my.cnf',
      },
 ...
```

instead of:

```
 DATABASES = {
      'default': {
      'NAME': 'calaccess_raw',
      'PASSWORD': 'ZuperZekretPazzword',
      'ENGINE': 'django.db.backends.mysql',
      'USER': 'ray',
      'HOST': 'localhost',
      'PORT': '3306',
      'OPTIONS': {
           'local_infile': 1,
      }
 }
```

See http://stackoverflow.com/questions/30447175/how-to-get-django-to-read-mysql-password-from-my-cnf

**Comment by adborden** [comment]
Good call. Django provides this by default, you can create a `settings_local.py` to overide project settings, including `DATABASES`. This should be documented in the README as the preferred way. I believe it is already in the gitignore.

**Comment by tdooner** [comment]
This is already the case for our production setup. It just so happens that the settings_local.py file there was created as a one-off undocumented process on our existing server, so it's understandable that you wouldn't know it exists. As for local credentials, I am not too concerned about people accidentally checking them in since they don't matter to anyone else.

I'm going to change this issue's title to reflect that this, at least the way I see it, is a documentation problem.

**Comment by bcipolli** [comment]
I believe this was fixed in https://github.com/caciviclab/disclosure-backend/commit/4ecb3d8f77c02b5eae7b8d2840f9ec6d0d787926#diff-04c6e90faac2675aa89e2176d2eec7d8R77

**Comment by tdooner** [comment]
Looks like it!
