### ISSUE TITLE
pip install can't find branch/tag specified in requirements.txt 

### ISSUE THREAD

**Issue by ebrensi** [caciviclab/disclosure-backend#71]
I just did a clean install of disclosure-backend and noticed that requirements.txt contains two specific branches/tags, one of which is 

```
-e git://github.com/caciviclab/django-calaccess-raw-data.git@0dd6b6913e4a00b49d1b9c9bf9829ed83f4587a3#egg=django-calaccess-raw-data
```

This one results in the message

```
Updating ./src/django-calaccess-raw-data clone (to 0dd6b6913e4a00b49d1b9c9bf9829ed83f4587a3)
  Could not find a tag or branch '0dd6b6913e4a00b49d1b9c9bf9829ed83f4587a3', assuming commit.
```

so I removed the branch/tag id from both requirements and it worked fine.  Not sure if this ok but it seems to work so far.  Before, I was ignoring these messages and it could be why I was experiencing other problems.

**Comment by tdooner** [comment]
This message is just a notice - Pip correctly resolves the `0dd6b6913e4a00b49d1b9c9bf9829ed83f4587a3` to be the commit SHA that we want to pin.

It's important that we pin the version of our dependencies so that we have consistent behavior regardless of what happens in that other repository, and we can explicitly opt-in to newer code when we please.
