### ISSUE TITLE
How-to doc to on-board a new jurisdiction

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#93]
We need a doc describing how a new jurisdiction gets into the system. This should live on the [wiki](https://github.com/caciviclab/caciviclab.github.io/wiki) as it's an evolving doc. Maybe we can document how San Diego gets involved.

**Comment by adborden** [comment]
Some high-level thoughts off the top of my head:
1. Add your group to our [contributors](http://caciviclab.org/#contributors).
2. Add your jurisdictions ballot information manually into the [ballot admin](http://admin.caciviclab.org/admin/ballot/).
3. Get your data into netfile? Or write an ETL to get it into ODCA.

**Comment by bcipolli** [comment]
Ya this is great, and we'd be happy to contribute.

I was thinking it'd be great to:
- Set everything up on a private test system (ballot measures, data scraping, cron tasks)
- When ready, have some deployment procedure, like:
  - Run a script to dump a fixture of ballot information from the test system.
  - Add the data to a branch for integration that includes the ETL scripts and any database info needed to run cron jobs.
  - When that branch is accepted into `master`, some scripts that admins can use to load the fixture(s) to get the ballot measures and cron data into the database. 

A lot of the specifics on how to get it done aren't clear to me (though to be fair, I spent most of my time so far engaging with the `calaccess_raw` project, not this one). Central workflow docs would be great on (for example):
- What's the relationships amongst ballot-related objects (so that we know what to enter where and how to inter-relate the data)?
- When we scrape & upload finance data to the DB, how do we relate it to the ballot measures?
- How are different jurisdictions handled (different DBs? different servers? or all kept together and filtered by the front-end?)
- How do we set up cron jobs for our scripts to be run nightly?

etc.

**Comment by bcipolli** [comment]
@adborden How's this look, to start?
https://github.com/caciviclab/caciviclab.github.io/wiki/On-boarding-a-new-city
